export const config = {
  emailUser: "sauravkumar001088@gmail.com",
  emailPassword: "piwjcexlbunkofxu", // this password is generated by gmail
};


//steps to generate password
//first go to gmail--> manage your google account--> security--> 2 factor verification should be on --> click on that --> go down, app password-- there you will get new generated password---> copy that password and use it.